`timescale 1ns/1ps

// ============================================================
// LACOODA CPU core — bus-handshake integration
//
// The core still decodes and executes the same Stage-7 ISA. The only
// architectural change here is how LOAD/STORE complete:
//
//   - dbus_valid is asserted for every LOAD/STORE request.
//   - dbus_write distinguishes STORE (1) from LOAD (0).
//   - address/write data remain stable while the instruction_word is held.
//   - a memory instruction_word is not architecturally complete until
//     dbus_ready is asserted by the external slave.
//   - LOAD writes RD only on the accepting bus handshake.
//
// Normal ALU and branch instructions remain fixed-latency and do not
// use the bus handshake.
// ============================================================

module cpu_core (
    input  logic clk,
    input  logic rst,

    input  logic core_enable,
    input  cpu_pkg::instruction_t instruction_word,
    input  cpu_pkg::word_t immediate_word,

    // Kept external to preserve the existing cpu_datapath interface.
    input  logic carry_in,

    // --------------------------------------------------------
    // Data-bus response from the external system.
    // dbus_rdata is consumed by LOAD when dbus_valid && dbus_ready.
    // --------------------------------------------------------
    input  logic dbus_ready,
    input  cpu_pkg::word_t dbus_rdata,

    output logic decode_valid,
    output logic illegal_instr,
    output logic retire_valid,

    // Stage 6 control-flow alu_result returned to the fetch wrapper.
    output logic redirect,
    output cpu_pkg::word_t redirect_target,

    // --------------------------------------------------------
    // Data-bus request generated by LOAD/STORE.
    //
    // Protocol:
    //   dbus_valid=1, dbus_write=0 : LOAD
    //   dbus_valid=1, dbus_write=1 : STORE
    //   transaction completes when dbus_valid && dbus_ready
    // --------------------------------------------------------
    output logic dbus_valid,
    output logic dbus_write,
    output cpu_pkg::word_t dbus_addr,
    output cpu_pkg::word_t dbus_wdata,

    output cpu_pkg::word_t operand_a,
    output cpu_pkg::word_t operand_b,
    output cpu_pkg::word_t alu_result,

    output cpu_pkg::flags_s flags,
    output cpu_pkg::status_t status
);

    cpu_pkg::reg_addr_t rs1;
    cpu_pkg::reg_addr_t rs2;
    cpu_pkg::reg_addr_t rd;

    opcode_pkg::opcode_t alu_op;
    cpu_pkg::word_t imm_operand;

    logic imm_sel;
    logic register_write_enable;
    logic flags_write_enable;
    logic alu_valid;

    // Stage 6 decoded branch controls.
    logic branch_enable;
    opcode_pkg::opcode_t branch_op;
    cpu_pkg::word_t branch_target;

    // Stage 7 decoded memory controls. These describe the instruction_word;
    // dbus_valid below additionally gates them with execution state.
    logic memory_read_enable;
    logic memory_write_enable;
    logic memory_op;

    cpu_pkg::word_t store_data;

    logic effective_register_write;
    logic effective_flags_write;

    // Multi-cycle execution state.
    typedef enum logic [1:0] {
        EX_IDLE,
        EX_ALU,
        EX_MEM
    } ex_state_e;

    ex_state_e ex_state;

    logic alu_start;
    logic alu_busy;
    logic alu_done;
    logic mem_accept;

    // --------------------------------------------------------
    // INSTRUCTION cpu_decoder
    // --------------------------------------------------------
    cpu_decoder u_cpu_decoder (
        .instruction(instruction_word),
        .immediate_word(immediate_word),

        .rs1(rs1),
        .rs2(rs2),
        .rd(rd),

        .alu_op(alu_op),
        .imm_operand(imm_operand),
        .imm_sel(imm_sel),

        .register_write_enable(register_write_enable),
        .flags_write_enable(flags_write_enable),

        .branch_enable(branch_enable),
        .branch_op(branch_op),
        .branch_target(branch_target),

        .memory_read_enable(memory_read_enable),
        .memory_write_enable(memory_write_enable),

        .decode_valid(decode_valid),
        .illegal_instr(illegal_instr)
    );

    // A decoded LOAD or STORE is a memory instruction_word. The cpu_decoder makes
    // these controls mutually exclusive for all legal instructions.
    assign memory_op =
        memory_read_enable || memory_write_enable;

    // --------------------------------------------------------
    // EXECUTION FSM
    //
    // Every decoded instruction runs the multi-cycle ALU. A LOAD/STORE
    // uses it to form the effective address; a branch uses the result
    // only as an observable value (the branch decision itself is made by
    // the combinational branch unit). Memory operations then wait for the
    // bus before retiring.
    // --------------------------------------------------------
    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            ex_state  <= EX_IDLE;
            alu_start <= 1'b0;
        end else begin
            alu_start <= 1'b0;

            case (ex_state)

                EX_IDLE: begin
                    if (core_enable && decode_valid && !rst) begin
                        alu_start <= 1'b1;
                        ex_state  <= EX_ALU;
                    end
                end

                EX_ALU: begin
                    if (alu_done)
                        ex_state <= memory_op ? EX_MEM : EX_IDLE;
                end

                EX_MEM: begin
                    if (mem_accept || !core_enable)
                        ex_state <= EX_IDLE;
                end

                default: ex_state <= EX_IDLE;

            endcase
        end
    end

    // --------------------------------------------------------
    // DATA BUS MASTER
    // --------------------------------------------------------
    // core_enable remains asserted while the wrapper stalls the PC,
    // therefore dbus_valid and all request payload signals remain asserted
    // and stable until dbus_ready completes the transaction. The request
    // only starts once the ALU has produced the effective address.
    assign dbus_valid =
        (ex_state == EX_MEM) &&
        core_enable &&
        decode_valid &&
        memory_op &&
        !rst;

    assign mem_accept = dbus_valid && dbus_ready;

    assign dbus_write = memory_write_enable;

    // LOAD/STORE use ALU_ADD, so alu_result is the effective byte address.
    assign dbus_addr = alu_result;
    assign dbus_wdata = store_data;

    // --------------------------------------------------------
    // ARCHITECTURAL WRITE ENABLES
    // --------------------------------------------------------
    // retire_valid marks the single cycle on which the instruction
    // completes, so it also gates the register/flags writes. A LOAD only
    // completes on the bus handshake, a normal instruction on alu_done.
    assign effective_register_write =
        register_write_enable && retire_valid;

    assign effective_flags_write =
        flags_write_enable && retire_valid;

    // --------------------------------------------------------
    // cpu_datapath
    // --------------------------------------------------------
    cpu_datapath u_cpu_datapath (
        .clk(clk),
        .rst(rst),

        .rs1(rs1),
        .rs2(rs2),
        .rd(rd),

        .alu_op(alu_op),
        .carry_in(carry_in),
        .alu_start(alu_start),

        .imm_operand(imm_operand),
        .imm_sel(imm_sel),

        .register_write_enable(effective_register_write),
        .flags_write_enable(effective_flags_write),

        .dmem_rdata(dbus_rdata),
        .writeback_from_mem(memory_read_enable),

        .operand_a(operand_a),
        .operand_b(operand_b),
        .store_data(store_data),
        .alu_result(alu_result),
        .alu_valid(alu_valid),
        .alu_busy(alu_busy),
        .alu_done(alu_done),

        .flags(flags),
        .status(status)
    );

    // --------------------------------------------------------
    // STAGE 6 BRANCH UNIT
    // --------------------------------------------------------
    branch_unit u_branch_unit (
        .enable(
            core_enable &&
            decode_valid &&
            branch_enable &&
            !rst
        ),
        .opcode(branch_op),
        .operand_a(operand_a),
        .operand_b(operand_b),
        .target(branch_target),
        .redirect(redirect),
        .redirect_target(redirect_target)
    );

    // retire_valid now means that the current instruction_word has actually
    // completed. Every instruction completes when the multi-cycle ALU
    // pulses done; a LOAD/STORE additionally waits until the bus slave
    // accepts the request.
    assign retire_valid =
        core_enable &&
        decode_valid &&
        !rst &&
        ( (!memory_op && alu_done) ||
          mem_accept );

endmodule
