`timescale 1ns/1ps

// ============================================================
// LACOODA CPU core — bus-handshake integration
//
// The core still decodes and executes the same Stage-7 ISA. The only
// architectural change here is how LOAD/STORE complete:
//
//   - bus_valid is asserted for every LOAD/STORE request.
//   - bus_write distinguishes STORE (1) from LOAD (0).
//   - address/write data remain stable while the instruction is held.
//   - a memory instruction is not architecturally complete until
//     bus_ready is asserted by the external slave.
//   - LOAD writes RD only on the accepting bus handshake.
//
// Normal ALU and branch instructions remain fixed-latency and do not
// use the bus handshake.
// ============================================================

module cpu_core (
    input  logic clk,
    input  logic rst,

    input  logic instruction_enable,
    input  cpu_pkg::instruction_t instruction,

    // Kept external to preserve the existing datapath interface.
    input  logic carry_in,

    // --------------------------------------------------------
    // Data-bus response from the external system.
    // bus_read_data is consumed by LOAD when bus_valid && bus_ready.
    // --------------------------------------------------------
    input  logic bus_ready,
    input  cpu_pkg::data_t bus_read_data,

    output logic instruction_valid,
    output logic illegal_instruction,
    output logic execution_valid,

    // Stage 6 control-flow result returned to the fetch wrapper.
    output logic redirect,
    output cpu_pkg::data_t redirect_target,

    // --------------------------------------------------------
    // Data-bus request generated by LOAD/STORE.
    //
    // Protocol:
    //   bus_valid=1, bus_write=0 : LOAD
    //   bus_valid=1, bus_write=1 : STORE
    //   transaction completes when bus_valid && bus_ready
    // --------------------------------------------------------
    output logic bus_valid,
    output logic bus_write,
    output cpu_pkg::data_t bus_address,
    output cpu_pkg::data_t bus_write_data,

    output cpu_pkg::data_t operand_a,
    output cpu_pkg::data_t operand_b,
    output cpu_pkg::data_t result,

    output alu_pkg::flags_t alu_flags,
    output alu_pkg::flags_t status_flags
);

    cpu_pkg::reg_addr_t rs1;
    cpu_pkg::reg_addr_t rs2;
    cpu_pkg::reg_addr_t rd;

    alu_pkg::opcode_t alu_op;
    cpu_pkg::data_t immediate;

    logic use_immediate;
    logic register_write_enable;
    logic flags_write_enable;
    logic alu_valid;

    // Stage 6 decoded branch controls.
    logic branch_enable;
    cpu_pkg::branch_condition_t branch_condition;
    cpu_pkg::data_t branch_target;

    // Stage 7 decoded memory controls. These describe the instruction;
    // bus_valid below additionally gates them with execution/reset state.
    logic decoded_memory_read_enable;
    logic decoded_memory_write_enable;
    logic memory_instruction;
    logic memory_complete;

    cpu_pkg::data_t store_data;

    logic effective_register_write;
    logic effective_flags_write;

    // --------------------------------------------------------
    // INSTRUCTION DECODER
    // --------------------------------------------------------
    decoder u_decoder (
        .instruction(instruction),

        .rs1(rs1),
        .rs2(rs2),
        .rd(rd),

        .alu_op(alu_op),
        .immediate(immediate),
        .use_immediate(use_immediate),

        .register_write_enable(register_write_enable),
        .flags_write_enable(flags_write_enable),

        .branch_enable(branch_enable),
        .branch_condition(branch_condition),
        .branch_target(branch_target),

        .memory_read_enable(decoded_memory_read_enable),
        .memory_write_enable(decoded_memory_write_enable),

        .instruction_valid(instruction_valid),
        .illegal_instruction(illegal_instruction)
    );

    // A decoded LOAD or STORE is a memory instruction. The decoder makes
    // these controls mutually exclusive for all legal instructions.
    assign memory_instruction =
        decoded_memory_read_enable || decoded_memory_write_enable;

    // Non-memory instructions complete without an external handshake.
    // Memory instructions complete only when the bus slave accepts them.
    assign memory_complete = !memory_instruction || bus_ready;

    // --------------------------------------------------------
    // DATA BUS MASTER
    // --------------------------------------------------------
    // instruction_enable remains asserted while the wrapper stalls the PC,
    // therefore bus_valid and all request payload signals remain asserted
    // and stable until bus_ready completes the transaction.
    assign bus_valid =
        instruction_enable &&
        instruction_valid &&
        memory_instruction &&
        !rst;

    assign bus_write = decoded_memory_write_enable;

    // LOAD/STORE use ALU_ADD, so result is the effective byte address.
    assign bus_address = result;
    assign bus_write_data = store_data;

    // --------------------------------------------------------
    // ARCHITECTURAL WRITE ENABLES
    // --------------------------------------------------------
    // A LOAD must not write its destination register while the external
    // memory transaction is still waiting. Normal instructions preserve
    // the original one-cycle write behavior.
    assign effective_register_write =
        instruction_enable &&
        instruction_valid &&
        register_write_enable &&
        memory_complete;

    assign effective_flags_write =
        instruction_enable &&
        instruction_valid &&
        flags_write_enable;

    // --------------------------------------------------------
    // DATAPATH
    // --------------------------------------------------------
    datapath u_datapath (
        .clk(clk),
        .rst(rst),

        .rs1(rs1),
        .rs2(rs2),
        .rd(rd),

        .alu_op(alu_op),
        .carry_in(carry_in),

        .immediate(immediate),
        .use_immediate(use_immediate),

        .register_write_enable(effective_register_write),
        .flags_write_enable(effective_flags_write),

        .memory_read_data(bus_read_data),
        .writeback_from_memory(decoded_memory_read_enable),

        .operand_a(operand_a),
        .operand_b(operand_b),
        .store_data(store_data),
        .result(result),
        .valid(alu_valid),

        .alu_flags(alu_flags),
        .status_flags(status_flags)
    );

    // --------------------------------------------------------
    // STAGE 6 BRANCH UNIT
    // --------------------------------------------------------
    branch_unit u_branch (
        .enable(
            instruction_enable &&
            instruction_valid &&
            branch_enable &&
            !rst
        ),
        .condition(branch_condition),
        .lhs(operand_a),
        .rhs(operand_b),
        .target(branch_target),
        .redirect(redirect),
        .redirect_target(redirect_target)
    );

    // execution_valid now means that the current instruction has actually
    // completed. A waiting LOAD/STORE is validly decoded but not complete.
    assign execution_valid =
        instruction_enable &&
        instruction_valid &&
        !rst &&
        (branch_enable || (alu_valid && memory_complete));

endmodule
